version: '3.8'

services:

  app:
    image: soumipandit/quicknotes-flask-mysql-docker:latest
    container_name: quicknotes_app
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: notesuser
      MYSQL_PASSWORD: notespass
      MYSQL_DB: quicknotes_db
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql:5.7
    container_name: quicknotes_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: quicknotes_db
      MYSQL_USER: notesuser
      MYSQL_PASSWORD: notespass
    ports:
      - "3306:3306"
    volumes:
      - quicknotes_mysql_data:/var/lib/mysql
    restart: always

volumes:
  quicknotes_mysql_data:
