version: '3.8'

services:

  app:
    image: soumipandit/quicknotes-flask-mysql-docker:latest
    container_name: quicknotes_app
    ports:
      - "5000:5000"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: notesuser
      MYSQL_PASSWORD: notespass
      MYSQL_DB: quicknotes_db
    restart: on-failure

  mysql:
    image: mysql:8.0
    container_name: quicknotes_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: quicknotes_db
      MYSQL_USER: notesuser
      MYSQL_PASSWORD: notespass
    ports:
      - "3306:3306"
    volumes:
      - quicknotes_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-unotesuser", "-pnotespass"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 40s

volumes:
  quicknotes_mysql_data:
    driver: local
